upstream django_app {
    server 127.0.0.1:8001;  # this line gets replaced by switch script
}

server {
    listen 80;

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
